name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: 16
      - name: Acceptance tests run
        uses: cypress-io/github-action@v4
        with:
          install-command: npm install --legacy-peer-deps
          start: npm start
          record: true
          command: npm run cypress:acceptance:prod
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Integration tests run
        uses: cypress-io/github-action@v4
        with:
          install-command: npm install --legacy-peer-deps
          start: npm start
          record: true
          command: npm run cypress:integration:prod
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}